apiVersion: v1
kind: Namespace
metadata:
  name: pedidos
  labels:
    name: pedidos
    environment: production
  name: production-manager-svc
  labels:
    name: production-manager
    environment: production