apiVersion: v1
kind: Secret
metadata:
  name: pedidos-secret
  namespace: pedidos
type: Opaque
data:
  # Substitua pela URL do banco codificada em base64
  # Exemplo: postgresql://fiap_arch:fiap_arch@<RDS_ENDPOINT>/<DB_NAME>
  DATABASE_URL: ""  # Você deve preencher isso com o valor codificado em base64